export class StepIndicator {
  DEFAULT:string;
  INDICATOR_CASE_ASSIGNMENT?: string; //COMPLETED IN PROGRESS
  INDICATOR_SCREENING_REVIEW?: string;
  INDICATOR_APPLICATION_REVIEW?: string;
  INDICATOR_PROPOSED_RESOLUTION?: string;
}
